Update Dockerfile_rocm64_base
Fix failed build

After a kernel update I got stuff like this causing failed build:
UserWarning: Cached asm caps differ from derived asm caps for (12, 0, 0)

ValueError: not enough values to unpack (expected 2, got 0)